export const artData = [
  {
    id: 1,
    title: "Logo_mobile",
    width: 150,
    height: 150,
    img: "./assets/tt_green_SF.gif",
    url: "#",
    color: "transparent",
  },
  {
    id: 2,
    title: "Logo_desk",
    width: 250,
    height: 250,
    img: "./assets/tt_green_SF.gif",
    url: "https://www.behance.net/matheusararipe",
    color: "transparent",
  },
  {
    id: 3,
    title: "clava",
    width: 200,
    height: 200,
    img: "./assets/clava_SF.gif",
    url: "https://www.behance.net/matheusararipe",
    color: "transparent",
  },
  {
    id: 4,
    title: "din",
    width: 340,
    height: 200,
    img: "./assets/din.gif",
    url: "https://www.behance.net/matheusararipe",
    color: "transparent",
  },
  {
    id: 5,
    title: "eye.dd",
    width: 220,
    height: 220,
    img: "./assets/img3.jpg",
    url: "https://www.behance.net/matheusararipe",
    color: "transparent",
  },
  {
    id: 6,
    title: "head_tt",
    width: 280,
    height: 180,
    img: "./assets/cabeca_tt.svg",
    url: "https://www.behance.net/matheusararipe",
    color: "#transparent",
  },
  {
    id: 7,
    title: "tt_gothic",
    width: 320,
    height: 220,
    img: "./assets/lettering_tt_sem_fundo.svg",
    url: "https://www.behance.net/matheusararipe",
    color: "#transparent",
  },
  // {
  //   id: 8,
  //   title: "tt_alt_logo",
  //   width: 300,
  //   height: 220,
  //   img: "./assets/ttx_favicon-04.svg",
  //   url: "https://www.behance.net/matheusararipe",
  //   color: "#transparent",
  // },
  {
    id: 9,
    title: "speak",
    width: 220,
    height: 220,
    img: "./assets/speak.gif",
    url: "https://www.behance.net/matheusararipe",
    color: "#transparent",
  },
  {
    id: 10,
    title: "Logo_desk_alt",
    width: 250,
    height: 250,
    img: "./assets/tt_orange_SF.gif",
    url: "https://www.behance.net/matheusararipe",
    color: "transparent",
  },
  {
    id: 11,
    title: "lollipop",
    width: 250,
    height: 250,
    img: "./assets/lollipop.gif",
    url: "https://www.behance.net/matheusararipe",
    color: "transparent",
  },
  {
    id: 12,
    title: "Saudades",
    width: 440,
    height: 250,
    img: "./assets/saudades_distort2.gif",
    url: "https://www.behance.net/matheusararipe",
    color: "transparent",
  },
  {
    id: 13,
    title: "vhs",
    width: 250,
    height: 250,
    img: "./assets/vhs_teste.jpg",
    url: "https://www.behance.net/matheusararipe",
    color: "transparent",
  },
  {
    id: 14,
    title: "btf",
    width: 200,
    height: 200,
    img: "./assets/SEM_FUNDO.png",
    url: "https://www.behance.net/matheusararipe",
    color: "transparent",
  },
  {
    id: 15,
    title: "ttx_aplic",
    width: 200,
    height: 200,
    img: "./assets/ttx_aplic.jpg",
    url: "https://www.behance.net/matheusararipe",
    color: "transparent",
  },
];
